### ISSUE TITLE
Upgrade ANTLR version to 4.10.1 or 4.13.x

### ISSUE THREAD

**Issue by nc-hlb** [OP-TED/eforms-core-java#29]
The current version of ANTLR is 4.9.3 which is not used for any hibernate version and causes compatibility issues. We have had to manually upgrade the project with 4.10.1 to work with hibernate (6.3.1). Newer Hibernate 6.4+ uses 4.13.0 and 4.13.1. 

The error is expressed as "ANTLR Tool version 4.9.3 does not match the current runtime version 4.10.1" when trying to parse EFX. This issue is a result of compiled code on EFXLexer, EFXParser, and XPath20Lexer which is compiled with a specific 4.9.x ANTLR and will not work with another 4.x version of ANTLR. ANTLR does not support backwards compatibility between these versions.

The fix is to just bump up the version of eforms-core-java and efx-toolkit-java. The tests pass from upgrading and recompiling the solution, as well as logically on our end.

**Comment by bertrand-lorentz** [comment]
Thanks for the suggestionand explanations, ANTLR 4.9 is indeed getting a bit old. We'll try to upgrade for the next release.

**Comment by bertrand-lorentz** [comment]
This is included in version 1.4.0, which was just released.
